### ISSUE TITLE
[Next Step] 2장 문자열 계산기 구현을 통한 테스트와 리팩토링

### ISSUE THREAD

**Issue by khg339** [CodeName-Onion/Onion-JAVA-NextStep-Study#1]
다음 스터디 시간(12월 19일)전까지 학습한 내용을 올려주세요.
원하는 방식으로 공부한 것을 편하게 올리면 됩니다. 아무거나 다 가능(양식 없음X)

실습코드는
1. 자신의 이름 폴더 만들기(내부에 chapter1, chapter2와 같이 단원 별로 정리)
2. '이름/study' 브랜치 파서 커밋
3. main에 머지

**Comment by khg339** [comment]
### 1. main() 문제점 및 JUnit 사용
https://velog.io/@khg339/Next-Step-%ED%85%8C%EC%8A%A4%ED%8A%B8%EC%99%80-%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81-1-JUnit
### 2. 문자열 계산기 실습
https://velog.io/@khg339/Next-Step-%ED%85%8C%EC%8A%A4%ED%8A%B8%EC%99%80-%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81-2-%EB%AC%B8%EC%9E%90%EC%97%B4-%EA%B3%84%EC%82%B0%EA%B8%B0-%EC%8B%A4%EC%8A%B5
### 3. 추가 학습 자료
진행 후 업데이트

**Comment by byulcode** [comment]
### 1. 테스트 코드
https://dandelion-terrier-f53.notion.site/Next-Step-Chanper2-19daa67b0564461ca7e2282a27718222

### 2. 문자열 계산기 실습
https://dandelion-terrier-f53.notion.site/Next-Step-Chapter2-8480a1de84104d729f88c3d98bfef2ad
