### ISSUE TITLE
[Next Step] 5장 : 리팩토링 시작

### ISSUE THREAD

**Issue by khg339** [CodeName-Onion/Onion-JAVA-NextStep-Study#10]
1.15 까지 리팩토링 후, 진행사항을 정리해주세요

**Comment by khg339** [comment]
[리팩토링 진행사항]
https://github.com/khg339/web-application-server

**Comment by khg339** [comment]
Controller 인터페이스, AbstractController 을 사용하는 과정에서 
상속의 개념과 extends, implements의 의미를 정확히 하기 위해 정리해보았다.

<hr>

부모의 변수와 메소드를 새로 구현하는가, 그대로 사용하는가에 따라 형태가 갈린다.

1. extends : 부모에서 선언 / 정의를 모두 하고, 자식은 메소드 / 변수를 **그대로 사용** 가능
2. implements : 부모 객체는 선언만 하며 정의는 **자식이 오버라이딩해서 사용**해야함
3. abstract : extends와 interface의 혼합. **extends 하되, 몇 개는 추상 메소드로 구현**돼 있음

<br/>

자바는 다중상속을 지원하지 않는다.
즉, 부모클래스가 두 개 이상 존재할 수 없다.

<br/>

**extends**의 경우, 그야말로 부모의 모든 것이 사용 가능하므로 상속 그 자체. **다중 사용 불가**
**implements**의 경우, **다중으로 사용이 가능**하다. 하지만 "모두" 재정의 해줘야함

<br/>

extends의 경우, 일반클래스와 abstract 클래스 상속에 사용되고,
implements의 경우 interface 상속에 사용된다.

<br/>

extends는 클래스를 "확장"하는 것이고, implements는 인터페이스를 "구현"하는 것이다.

**Comment by khg339** [comment]
RequestMapping 작성 시, 왜 모두 static을 사용했을까?
보통 static의 사용을 지양하는데, 왜 Mapping 클래스를 구현할 때는 static이 사용되었을까

<hr>

객체의 상태를 이용할 생각이 없고, 
여러 객체들의 필요에 의해 데이터를 처리하는 공통 로직이 필요할 때는 static을 사용하여 설계하는 것이 좋다.

-> mapping은 여러 Controller 객체들에게 같은 로직의 처리를 진행하므로 위의 경우와 같은 경우다.

**Comment by byulcode** [comment]
5장 리팩토링
https://dandelion-terrier-f53.notion.site/Next-Step-5-1-5944ca6faf7e47d78c0083850d7c1f0c

서블릿
https://dandelion-terrier-f53.notion.site/Next-Step-5-1-5944ca6faf7e47d78c0083850d7c1f0c

**Comment by khg339** [comment]
5장 리팩토링 정리
https://velog.io/@khg339/Next-Step-5%EC%9E%A5-%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81%EA%B3%BC-%ED%85%8C%EC%8A%A4%ED%8A%B8%EC%BD%94%EB%93%9C
