### ISSUE TITLE
[1.26] 스터디 8회차 진행상황

### ISSUE THREAD

**Issue by byulcode** [CodeName-Onion/Onion-JAVA-NextStep-Study#12]
1. 6장 MVC 프레임워크 구현
2. 다음 스터디 계획

**Comment by byulcode** [comment]
[6장 진행과정]
https://dandelion-terrier-f53.notion.site/Next-Step-6-2-MVC-1c6422224a924ccea881e99dbfdf2e8d

[인프런 강의 - MVC 패턴]
https://dandelion-terrier-f53.notion.site/3-1-MVC-1-b2c868e4af6a42b9af2acb89573a7e7e

**Comment by khg339** [comment]
https://velog.io/@khg339/Next-Step-6%EC%9E%A5-MVC-%ED%94%84%EB%A0%88%EC%9E%84%EC%9B%8C%ED%81%AC
