### ISSUE TITLE
[Next Step] 3장 시작 준비 : 자바의 스레드, 입출력 스트림

### ISSUE THREAD

**Issue by khg339** [CodeName-Onion/Onion-JAVA-NextStep-Study#3]
다음 스터디 시간(12월 25일)전까지 학습한 내용을 올려주세요.
원하는 방식으로 공부한 것을 편하게 올리면 됩니다. 아무거나 다 가능(양식 없음X)

**Comment by khg339** [comment]
"Do it 자바 완전 정복" 교재의 15장 쓰레드

동영상 강의 주소 : https://www.youtube.com/watch?v=vKgDXrN5zAQ&list=PLR9w0n2BH7rci0nw5SGiYN0-Ded98-Ew5&index=1
<hr>

강의를 들으며 메모장에 정리해서 공부했습니다.

[쓰레드.txt](https://github.com/CodeName-Onion/Onion-JAVA-NextStep-Study/files/10298848/default.txt)

아직 velog 업로드는 못했는데, 내용 정리하면서 + 머릿속 정리도 하면서 velog 업로드도 해서 올리겠습니다!

입출력 스트림은 아직 공부하지 못해서 쓰레드 관련으로만 문제 제출 했습니다.
(쓰레드도 동기화 초반까지만 진행했습니다..)

**Comment by byulcode** [comment]
https://dandelion-terrier-f53.notion.site/8-b6e7fb788bd84f279cd4bb1b6eab3126

**Comment by khg339** [comment]
다음 스터디 시간(12월 27일)전까지 학습한 내용을 올려주세요.
원하는 방식으로 공부한 것을 편하게 올리면 됩니다. 아무거나 다 가능(양식 없음X)

**Comment by khg339** [comment]
Thread 정리 velog

https://velog.io/@khg339/%EC%93%B0%EB%A0%88%EB%93%9CThread%EC%9D%98-%EB%AA%A8%EB%93%A0-%EA%B2%83

**Comment by byulcode** [comment]
스트림 정리
https://dandelion-terrier-f53.notion.site/Next-Step-3-1-Stream-cecac73012504e49a7a82d2d88e90d9c

번외)스트림 api 정리
https://dandelion-terrier-f53.notion.site/Stream-API-ecd1803bd17d45e4b6a1b9ae6370af2a
