### ISSUE TITLE
[Next Step] 3장 : 구현 시작

### ISSUE THREAD

**Issue by khg339** [CodeName-Onion/Onion-JAVA-NextStep-Study#8]
1월 3일까지 3장 구현 사항을 원하는 양식으로 공유해주세요
코드는 main에 merge 해주세요

**Comment by byulcode** [comment]
보조 스트림 추가 정리
[Next_Step__3.2_-_보조_스트림.pdf](https://github.com/CodeName-Onion/Onion-JAVA-NextStep-Study/files/10328188/Next_Step__3.2_-_._.pdf)

**Comment by khg339** [comment]
로그 사용 시 참고한 블로그
https://cornarong.tistory.com/35

**Comment by khg339** [comment]
1월 12일까지 3장 구현 완료 및 4장을 통한 코드 수정 해주세요.
완료한 후 github 주소 및 정리한 내용 올려주세요

**Comment by khg339** [comment]
3장 코드 구현 완료

- 깃허브(구현코드) : https://github.com/khg339/web-application-server
- velog(정리한 내용) : https://velog.io/@khg339/Next-Step-3%EC%9E%A5-%EA%B0%9C%EB%B0%9C-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95-%EB%B0%8F-%EC%84%9C%EB%B2%84-%EC%8B%A4%EC%8A%B5-%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD

**Comment by byulcode** [comment]
HTTP 관련 정보 정리본
[인프런_2_-_HTTP웹_네트워크.pdf](https://github.com/CodeName-Onion/Onion-JAVA-NextStep-Study/files/10365311/_2_-_HTTP._.pdf)

**Comment by khg339** [comment]
4장 공부하며 정리한 내용

https://velog.io/@khg339/Next-Step-HTTP-%EC%9B%B9-%EC%84%9C%EB%B2%84-%EC%9D%B4%ED%95%B4

**Comment by byulcode** [comment]
3장 코드 구현
https://dandelion-terrier-f53.notion.site/Next-Step-3-3-794a8f564a684dcdbce84ea4ec2c06c3
4장 공부 내용
https://dandelion-terrier-f53.notion.site/Next-Step-4-1-HTTP-HTTP-04853f7836ba48a197596ff560953396

**Comment by byulcode** [comment]
Q1. HTTP 요청 라인에는 HTTP 메소드가 쓰여 있다. 이 메소드는 html파일의 어떤 태그의 어떤 속성의 값에 따라 생성되는가?

Q2. POST 방식으로 회원가입 처리를 완료한 후 상태코드 200, 요청 URL 값을 /index.html로 보내 index.html 화면이 열리도록 했다. 그런데 이때 웹 브라우저를 새로고침 하면 이전과 똑같은 회원가입 요청이 발생하여 데이터가 중복 전송된다. 그 이유는 무엇이며, 해결하려면 어떻게 해야 하는가?

Q3. HTTP에서 쿠키를 사용하는 이유가 무엇인가?
